Repository petgraph/petgraph, pull requests merged in 2021-06, with the labels that each got.

#441 Update Cargo.toml
  Cargo.toml
Labels: documentation

#442 Avoid creating dummy NodeIds in maximum_matching
  src/matching.rs
Labels: bug

#440 Fix minor clippy warnings
  Cargo.toml
  src/adj.rs
  src/algo/bellman_ford.rs
  src/algo/dominators.rs
  src/algo/mod.rs
  src/csr.rs
  src/floyd_warshall.rs
  src/graph_impl/mod.rs
  src/isomorphism.rs
  src/matching.rs
  src/matrix_graph.rs
  src/visit/mod.rs
Labels: enhancement
