Repository petgraph/petgraph, pull requests merged in 2021-05, with the labels that each got.

#427 Fix various bugs in matrix graph
  src/matrix_graph.rs
Labels: bug

#432 Fix GraphMap::remove_node not removing some edges
  src/graphmap.rs
  tests/graphmap.rs
Labels: bug

#433 Specify that IntoEdges must have `a` as source
  src/visit/mod.rs
Labels: breaking-change, documentation

#429 Implement multiple missing graph traits
  src/adj.rs
  src/csr.rs
  src/graph_impl/frozen.rs
  src/graph_impl/mod.rs
  src/graphmap.rs
  src/matrix_graph.rs
  src/visit/filter.rs
  src/visit/reversed.rs
  tests/graphmap.rs
  tests/iso.rs
Labels: breaking-change, enhancement

#395 Improve StableGraph de-serialization with holes
  Cargo.toml
  benches/serialize.rs
  serialization-tests/tests/serialization.rs
  src/graph_impl/serialization.rs
  src/graph_impl/stable_graph/serialization.rs
  src/util.rs
Labels: enhancement
