Repository petgraph/petgraph, pull requests merged in 2025-06, with the labels that each got.

#807 docs: Update docs.rs
  README.md
  src/lib.rs
Labels: documentation

#814 docs: Clarification of references to nodes and V (refresh #358)
  src/algo/bridges.rs
  src/algo/dominators.rs
  src/algo/mod.rs
  src/algo/page_rank.rs
  src/csr.rs
  src/generate.rs
  src/graph_impl/mod.rs
  src/graph_impl/stable_graph/mod.rs
  src/graphmap.rs
  src/matrix_graph.rs
  src/visit/dfsvisit.rs
Labels: documentation

#816 docs: Fix link and mention Dfs and Bfs as special case in examples
  src/lib.rs
  src/visit/traversal.rs
Labels: documentation

#815 docs: Unify algo docs
  src/algo/articulation_points.rs
  src/algo/astar.rs
  src/algo/bellman_ford.rs
  src/algo/bridges.rs
  src/algo/coloring.rs
  src/algo/dijkstra.rs
  src/algo/dominators.rs
  src/algo/feedback_arc_set.rs
  src/algo/floyd_warshall.rs
  src/algo/ford_fulkerson.rs
  src/algo/johnson.rs
  src/algo/k_shortest_path.rs
  src/algo/matching.rs
  src/algo/maximal_cliques.rs
  src/algo/min_spanning_tree.rs
  src/algo/mod.rs
  src/algo/page_rank.rs
  src/algo/simple_paths.rs
  src/algo/spfa.rs
  src/algo/steiner_tree.rs
  src/algo/tred.rs
Labels: documentation

#824 docs: Add link to multigraph definition to isomorphism algos
  src/algo/isomorphism.rs
Labels: documentation

#822 test: Add dependency list for 'quickcheck' feature
  Cargo.toml
Labels: C-bugfix, A-deps

#767 chore: Trim the `hashbrown` dependencies
  Cargo.toml
Labels: A-deps

#831 docs: Fix Typo in Operator Module Documentation
  src/operator.rs
Labels: A-documentation

#830 refactor: add examples for scc algorithms and reorganize into dedicated module
  src/algo/mod.rs
  src/algo/scc/kosaraju_scc.rs
  src/algo/scc/mod.rs
  src/algo/scc/tarjan_scc.rs
  src/visit/traversal.rs
Labels: A-documentation

#832 docs: Sync the crate feature flags in the README and docs
  README.md
  src/lib.rs
Labels: A-documentation

#835 docs: Remove all \[Generic\] tags from algo docstrings
  src/algo/articulation_points.rs
  src/algo/astar.rs
  src/algo/bellman_ford.rs
  src/algo/coloring.rs
  src/algo/dijkstra.rs
  src/algo/feedback_arc_set.rs
  src/algo/floyd_warshall.rs
  src/algo/ford_fulkerson.rs
  src/algo/isomorphism.rs
  src/algo/johnson.rs
  src/algo/k_shortest_path.rs
  src/algo/matching.rs
  src/algo/min_spanning_tree.rs
  src/algo/mod.rs
  src/algo/page_rank.rs
  src/algo/scc/kosaraju_scc.rs
  src/algo/scc/tarjan_scc.rs
  src/algo/spfa.rs
  src/algo/steiner_tree.rs
Labels: A-documentation

#838 ci: Compare `spfa` with `bellman_ford` in quickchecks
  tests/quickcheck.rs
Labels: A-ci, C-refactor
