Repository petgraph/petgraph, pull requests merged in 2025-03, with the labels that each got.

#682 feat: Add Kou's algorithm for finding a MST
  src/algo/dijkstra.rs
  src/algo/floyd_warshall.rs
  src/algo/mod.rs
  src/algo/steiner_tree.rs
  tests/quickcheck.rs
  tests/steiner_trees.rs
Labels: C-new-algorithm

#662 feat: Add Bron-Kerbosch algorithm for maximal cliques
  benches/maximal_cliques.rs
  src/algo/maximal_cliques.rs
  src/algo/mod.rs
  tests/maximal_cliques.rs
  tests/quickcheck.rs
Labels: C-new-algorithm

#686 feat: Add Shortest Path Faster Algorithm Implementation
  benches/spfa.rs
  src/algo/mod.rs
  src/algo/spfa.rs
  tests/quickcheck.rs
  tests/spfa.rs
Labels: C-new-algorithm, performance

#728 feat!: Add support for specifying rankdir on dot plots.
  src/dot.rs
Labels: breaking-change

#733 feat!: Add `from_f32/64` methods for `Float`, `Unit`, and `Bounded` measures
  src/algo/mod.rs
Labels: breaking-change
