Repository petgraph/petgraph, pull requests merged in 2025-07, with the labels that each got.

#828 refactor: Remove unnecessary trait bounds from impls/methods
  src/graph_impl/mod.rs
  src/graph_impl/stable_graph/mod.rs
  src/graphmap.rs
Labels: A-crate, C-feature-accepted, S-waiting-on-review

#849 refactor: replace uses of 'crate::util::zip' with 'core::iter::zip'
  src/csr.rs
  src/util.rs
Labels: A-crate, C-refactor, S-waiting-on-review

#851 refactor: Fix clippy (and other) lints
  src/graph_impl/mod.rs
  src/graph_impl/stable_graph/mod.rs
  src/graphmap.rs
  src/iter_format.rs
  src/matrix_graph.rs
Labels: A-crate, C-refactor

#852 test: Fix feature cfg capitalization in doctest
  src/lib.rs
Labels: A-documentation

#845 ci: Use just and adapt CONTRIBUTING.md and ci.yml accordingly
  .github/workflows/ci.yml
  CONTRIBUTING.md
  justfile
Labels: A-readme, S-waiting-on-review

#857 docs: Update `GraphMap` link in README
  README.md
Labels: A-readme
