Repository petgraph/petgraph, pull requests merged in 2025-09, with the labels that each got.

#863 feat: Add `map_owned` and `filter_map_owned` for `Graph` and `StableGraph`
  src/graph_impl/mod.rs
  src/graph_impl/stable_graph/mod.rs
  tests/graph.rs
  tests/stable_graph.rs
Labels: A-crate, C-feature-accepted, S-waiting-on-review

#865 feat: Fix self-loop bug in all_simple_paths and enable multiple targets
  benches/simple_paths.rs
  src/algo/mod.rs
  src/algo/simple_paths.rs
Labels: C-bugfix, C-feature-accepted, S-waiting-on-review

#850 docs: Add doc comment for `Dot::with_attr_getters`
  src/dot/mod.rs
Labels: S-waiting-on-author, A-documentation

#782 feat: Add bidirectional Dijkstra algorithm
  benches/dijkstra.rs
  src/algo/dijkstra.rs
  src/algo/mod.rs
  tests/quickcheck.rs
Labels: C-new-algorithm, C-feature-accepted, S-waiting-on-review

#790 docs: Specify iteration order for neighbors and edges and their variants
  src/graph_impl/mod.rs
  src/graph_impl/stable_graph/mod.rs
  tests/graph.rs
  tests/stable_graph.rs
Labels: A-documentation, S-waiting-on-review

#882 perf: Make A* tie break on lower h-values
  benches/astar.rs
  benches/common/factories.rs
  benches/dijkstra.rs
  src/algo/astar.rs
  tests/graph.rs
  tests/quickcheck.rs
Labels: C-performance, A-benches, A-crate, S-waiting-on-review

#887 ci: Use new cargo resolver when running CI with MSRV
  .github/workflows/ci.yml
Labels: C-bugfix, A-ci
